spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

yookassa.shop-id=1262297
yookassa.secret-key=test_HaQ063ykhlxr3GPaq5VTiNn_ofGZJSMXuwqX3EMz9j0
yookassa.return-url=washingapp://payment-return